### ISSUE TITLE
Memory leak with `FabricItemStorage` in 1.20.1

### ISSUE THREAD

**Issue by solonovamax** [Wilyicaro/FactoryAPI#2]
Hi,

I believe there is a memory leak with in fabric 1.20.1, somewhere to do with `FabricItemStorage`.

I'm inspecting a heap dump, and there are >1gb of references to `net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl` and `net.fabricmc.fabric.impl.transfer.item.InventorySlotWrapper`, and if I follow the tree of referrers, the class `wily.factoryapi.fabric.base.FabricItemStorage` repeatedly pops up.

additionally, I am seeing instances of `wily.betterfurnaces.blockentity.ForgeBlockEntity`, so it may have smth to do with that.

the issue is severe enough that it will exhaust 16gb of heap in ~3 hours.

also, I see that on yhe `FabricItemStorage` instances, they have `transportState` set to `EXTRACT_INSERT`. not sure if that will help narrow down the source.

**Comment by Wilyicaro** [comment]
Sorry for the delay in responding, it was fixed in version 2.1, if you have any problems with this issue again, just let me know here

**Comment by solonovamax** [comment]
Alright, I will attempt to reproduce this later, to see if I can.

That single commit is quite big though, so just from looking at it, I can't tell what change would have patched this so it'd be difficult to investigate it more myself if it does still occur lol
