### ISSUE TITLE
Crash with Thermal Series machines

### ISSUE THREAD

**Issue by muggleorwizard** [Wilyicaro/FactoryAPI#3]
There is a crash that occurs when shift-clicking items that require power into thermal machines. According to the COFH core support, the fix is to remove FactoryAPI. Is there a way you can fix this so I can keep using yor mod in my pack? I have the crash report and screenshot of reply below.

https://pastebin.com/frcA6GNG

![Screenshot_20240126_092729_Discord](https://github.com/Wilyicaro/FactoryAPI/assets/156606937/b320a1f8-25fc-434f-9e63-be11165c1015)

**Comment by Wilyicaro** [comment]
Fixed in 2.1 version, thanks for reporting.
