### ISSUE TITLE
[Bug] Netherhot Furnace + Generator Upgrade crash

### ISSUE THREAD

**Issue by muggleorwizard** [Wilyicaro/FactoryAPI#5]
### Better Furnaces Reforged Version

1.20.1-1.1.3

### Mod Loader Version

Forge 47.2.20

### Bug/Glitch Occurrence Context

Netherhot Furnace + Generator Upgrade crash

### Crash Report

https://pastebin.com/ShsJt7qj

### What happened wrong?

When shift-clicking or placing a generator upgrade into a netherhot furnace, the server/world will close.

**Comment by Wilyicaro** [comment]
Fixed in Factory API 1.20.4-2.1.3 and 1.20.1-2.1.4, thanks for reporting.
